#!/usr/bin/env ruby
#
# git-rewrite-dates
# Rewrites the author-date and committer-date on commits you haven't pushed to
# the present time, after prompting for confirmation. Use -q or --quiet to skip
# the confirmation.
#
# Usage:
#   git rewrite-dates [-q]

def dirty?
  `git diff-files --quiet`
  $?.exitstatus.nonzero?
end

def quiet?
  abort "Too many arguments" if ARGV.size > 1
  quiet = ARGV[0] =~ /^-q|--quiet$/
  abort "Unknown argument #{ARGV[0]}" if quiet.nil? && ARGV.any?
  quiet
end

def refs_notpushed_chronologically
  `git notpushed --pretty=format:%H`.split("\n").map { |sha| sha.strip }.reverse
end

def rewrite_local_commit_timestamps
  commit_count = refs_notpushed_chronologically.size
  commit_count.times do |i|
    ref = refs_notpushed_chronologically[i]
    env_filter = %Q|if [ "$GIT_COMMIT" = "#{ref}" ]; then export GIT_AUTHOR_DATE="#{Time.now + i}" && export GIT_COMMITTER_DATE="#{Time.now + i}"; fi|
    `git filter-branch --force --env-filter '#{env_filter}' #{ref}~..HEAD`
  end
end

abort "Cannot rewrite branch with a dirty working directory." if dirty?

unless quiet?
  print "\nRewrite the dates of un-pushed commits to the current time? [y/N] "
  exit unless gets =~ /y(es)?/i
end

rewrite_local_commit_timestamps
