#!/usr/bin/env ruby
#
# git-pair
# Changes git's user.name and user.email to include the information of more than
# one programmer. The names are chosen from a list which is itself stored in
# git-config. The email address is composed from a template value in git-config
# and the developers' initials.
#
# Notes:
#
#   Set the email address template:
#   git config git-pair.email dev@example.com
#
#   Add authors:
#   git config --add git-pair.authors "Linus Torvalds"
#   git config --add git-pair.authors "Junio C Hamano"

class String
  def initials
    split.map { |word| word[0].chr.upcase }.join
  end
end

def author_names
  names = `git config --get-all git-pair.authors`.split("\n")
  names.sort_by { |name| name.split.last }
end

def print_authors
  author_names.each do |name|
    puts "#{name.initials} => #{name}"
  end
end

`git config --get git-pair.email`

print_authors
